name: cd_netify_dbt_docs

on:
  push:
    branches: [ "netify_dbt_docs" ]
  pull_request:
    branches: [ "netify_dbt_docs" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish-dbt-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trigger build
        run: curl -X POST -d '{}' ${{ secrets.NETIFY_BUILD_URL }}
